version: '3.9'

services:
  # Servidor Samba para respaldos
  respaldo-server:
    build:
      context: ./servidor-respaldo
      dockerfile: Dockerfile
    container_name: respaldo-server
    ports:
      - "1445:445"
      - "1139:139"
    volumes:
      - respaldo_data:/srv/respaldo
    networks:
      - red_respaldo
    restart: unless-stopped

  # Cliente Linux con cron
  cliente-linux:
    build:
      context: .
      dockerfile: cliente-linux/Dockerfile
    container_name: cliente-linux
    depends_on:
      - respaldo-server
    networks:
      - red_respaldo
    volumes:
      - ./pruebas_cliente:/home/respaldo_origen
    restart: unless-stopped

volumes:
  respaldo_data:

networks:
  red_respaldo:
    driver: bridge
